return {
{'Ada', visible = false, action = function() return scite.SetLexer('ads') end, check = "editor.LexerLanguage == 'ada'"},
{'ABAP', visible = false, action = function() return scite.SetLexer('abap') end, check = "editor.LexerLanguage == 'abap'"},
{'AutoIt3', visible = false, action = function() return scite.SetLexer('au3') end, check = "editor.LexerLanguage == 'autoit3'"},
{'Apache Confi&g', visible = false, action = function() return scite.SetLexer('conf') end, check = "editor.LexerLanguage == 'apache config'"},
{'Assembler', visible = false, action = function() return scite.SetLexer('asm') end, check = "editor.LexerLanguage == 'assembler'"},
{'ASN.1', visible = false, action = function() return scite.SetLexer('asn1') end, check = "editor.LexerLanguage == 'asn.1'"},
{'Avenue', visible = false, action = function() return scite.SetLexer('ave') end, check = "editor.LexerLanguage == 'avenue'"},
{'Baan', visible = false, action = function() return scite.SetLexer('bc') end, check = "editor.LexerLanguage == 'baan'"},
{'Basic', visible = false, action = function() return scite.SetLexer('bas') end, check = "editor.LexerLanguage == 'basic'"},
{'&Batch', action = function() return scite.SetLexer('bat') end, check = "editor.LexerLanguage == 'batch'"},
{'Bullant', visible = false, action = function() return scite.SetLexer('ant') end, check = "editor.LexerLanguage == 'bullant'"},
{'&C / C++', action = function() return scite.SetLexer('c') end, check = "editor.LexerLanguage == 'cpp'"},
{'CMake', visible = false, action = function() return scite.SetLexer('cmake') end, check = "editor.LexerLanguage == 'cmake'"},
{'C&#', visible = false , action = function() return scite.SetLexer('cs') end, check = "editor.LexerLanguage == 'c#'"},
{'Csound', visible = false, action = function() return scite.SetLexer('orc') end, check = "editor.LexerLanguage == 'csound'"},
{'CSS', visible = false, action = function() return scite.SetLexer('css') end, check = "editor.LexerLanguage == 'css'"},
{'D', visible = false, action = function() return scite.SetLexer('d') end, check = "editor.LexerLanguage == 'd'"},
{'&Difference', action = function() return scite.SetLexer('diff') end, check = "editor.LexerLanguage == 'diff'"},
{'&Eiffel', visible = false, action = function() return scite.SetLexer('e') end, check = "editor.LexerLanguage == 'eiffel'"},
{'Erlang', visible = false, action = function() return scite.SetLexer('erl') end, check = "editor.LexerLanguage == 'erlang'"},
{'&Errorlist', action = function() return scite.SetLexer('err') end, check = "editor.LexerLanguage == 'diff'"},
{'FlagShip', visible = false, action = function() return scite.SetLexer('prg') end, check = "editor.LexerLanguage == 'flagship'"},
{'Forth', visible = false, action = function() return scite.SetLexer('forth') end, check = "editor.LexerLanguage == 'forth'"},
{'&Fortran', visible = false, action = function() return scite.SetLexer('f90') end, check = "editor.LexerLanguage == 'fortran'"},
{'Gap', visible = false, action = function() return scite.SetLexer('g') end, check = "editor.LexerLanguage == 'gap'"},
{'H&ypertext', action = function() return scite.SetLexer('html') end, check = "editor.LexerLanguage == 'hypertext'"},
{'&InnoSetup', visible = false, action = function() return scite.SetLexer('iss') end, check = "editor.LexerLanguage == 'innosetup'"},
{'&Java', visible = false, action = function() return scite.SetLexer('java') end, check = "editor.LexerLanguage == 'java'"},
{'Java&Script', action = function() return scite.SetLexer('js') end, check = "editor.LexerLanguage == 'javascript'"},
{'&Kix', visible = false, action = function() return scite.SetLexer('kix') end, check = "editor.LexerLanguage == 'kix'"},
{'TeX', visible = false, action = function() return scite.SetLexer('tex') end, check = "editor.LexerLanguage == 'tex'"},
{'Lisp', visible = false, action = function() return scite.SetLexer('lisp') end, check = "editor.LexerLanguage == 'lisp'"},
{'Lot', visible = false, action = function() return scite.SetLexer('lot') end, check = "editor.LexerLanguage == 'lot'"},
{'Lout', visible = false, action = function() return scite.SetLexer('lt') end, check = "editor.LexerLanguage == 'lout'"},
{'Lu&a', action = function() return scite.SetLexer('lua') end, check = "editor.LexerLanguage == 'lua'"},
{'Matlab', visible = false, action = function() return scite.SetLexer('m.matlab') end, check = "editor.LexerLanguage == 'matlab'"},
{'&Makefile', visible = false, action = function() return scite.SetLexer('mak') end, check = "editor.LexerLanguage == 'makefile'"},
{'MetaPost', visible = false, action = function() return scite.SetLexer('mp') end, check = "editor.LexerLanguage == 'metapost'"},
{'MMIXAL', visible = false, action = function() return scite.SetLexer('mms') end, check = "editor.LexerLanguage == 'mmixal'"},
{'&nnCron crontab', visible = false, action = function() return scite.SetLexer('tab') end, check = "editor.LexerLanguage == 'nncron crontab'"},
{'NSIS', visible = false, action = function() return scite.SetLexer('nsis') end, check = "editor.LexerLanguage == 'nsis'"},
{'Objective Caml', visible = false, action = function() return scite.SetLexer('ml') end, check = "editor.LexerLanguage == 'objective caml'"},
{'Octave', visible = false, action = function() return scite.SetLexer('m.octave') end, check = "editor.LexerLanguage == 'octave'"},
{'Opal', visible = false, action = function() return scite.SetLexer('impl') end, check = "editor.LexerLanguage == 'opal'"},
{'Pascal', visible = false, action = function() return scite.SetLexer('pas') end, check = "editor.LexerLanguage == 'pascal'"},
{'Pe&rl', visible = false, action = function() return scite.SetLexer('pl') end, check = "editor.LexerLanguage == 'perl'"},
{'P&HP', visible = false, action = function() return scite.SetLexer('php') end, check = "editor.LexerLanguage == 'php'"},
{'P&LSQL', visible = false, action = function() return scite.SetLexer('spec') end, check = "editor.LexerLanguage == 'plsql'"},
{'&Properties', action = function() return scite.SetLexer('properties') end, check = "editor.LexerLanguage == 'props'"},
{'P&ostScript', visible = false, action = function() return scite.SetLexer('ps') end, check = "editor.LexerLanguage == 'postscript'"},
{'P&OV-Ray SDL', visible = false, action = function() return scite.SetLexer('pov') end, check = "editor.LexerLanguage == 'pov-ray sdl'"},
{'PowerShell', visible = false, action = function() return scite.SetLexer('ps1') end, check = "editor.LexerLanguage == 'powershell'"},
{'Pytho&n', visible = false, action = function() return scite.SetLexer('py') end, check = "editor.LexerLanguage == 'python'"},
{'R', visible = false, action = function() return scite.SetLexer('R') end, check = "editor.LexerLanguage == 'r'"},
{'Reso&urce', visible = false, action = function() return scite.SetLexer('rc') end, check = "editor.LexerLanguage == 'resource'"},
{'Ruby', visible = false, action = function() return scite.SetLexer('rb') end, check = "editor.LexerLanguage == 'ruby'"},
{'Shell', visible = false, action = function() return scite.SetLexer('sh') end, check = "editor.LexerLanguage == 'shell'"},
{'S&QL', action = function() return scite.SetLexer('sql') end, check = "editor.LexerLanguage == 'sql'"},
{'Specman', visible = false, action = function() return scite.SetLexer('e') end, check = "editor.LexerLanguage == 'specman'"},
{'&TCL', visible = false, action = function() return scite.SetLexer('tcl') end, check = "editor.LexerLanguage == 'tcl'"},
{'&VB', action = function() return scite.SetLexer('vb') end, check = "editor.LexerLanguage == 'vb'"},
{'VBScr&ipt', action = function() return scite.SetLexer('vbs') end, check = "editor.LexerLanguage == 'vbscript'"},
{'Verilog', visible = false, action = function() return scite.SetLexer('v') end, check = "editor.LexerLanguage == 'verilog'"},
{'VHDL', visible = false, action = function() return scite.SetLexer('vhd') end, check = "editor.LexerLanguage == 'vhdl'"},
{'FormEnjine', action = function() return scite.SetLexer('formenjine') end, check = "editor.LexerLanguage == 'formenjine'"},
{'&XML', action = function() return scite.SetLexer('rdf') end, check = "editor.LexerLanguage == 'xml'"},
{'YAML', visible = false, action = function() return scite.SetLexer('yaml') end, check = "editor.LexerLanguage == 'yaml'"},
{'M', visible = false, action = function() return scite.SetLexer('m') end, check = "editor.LexerLanguage == 'm'"},
}
